### Kelly Tornetta
### Smith-Waterman Algorithm

In [1]:
import random
import string
import numpy as np

In [2]:
#function outputs random string of a certain length and number of characters

def random_string(length, num_char):
    if num_char < 1: 
        print("ERROR: Needs at least one character.")
        return 0
    elif num_char > 26:
        print("ERROR: Maximum number of characters is 26.")
        return 0
    letters = string.ascii_lowercase[0:num_char]
    output = ''.join(random.choice(letters) for i in range(length))
    return output

Testing:

In [3]:
random_string(10,4)

'dcccdccbaa'

### H matrix in the Smith-Waterman Algo - bottom up

In [4]:
def smith_matrix(X, Y):
    n, m = len(X), len(Y)
    H = np.zeros((n + 1, m + 1), np.int)
    
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            if X[i-1] == Y[j-1]:
                p1 = H[i-1, j-1] + 2
            else:
                p1 = H[i-1, j-1] - 1
            p2 = H[i-1, j] - 1
            p3 = H[i, j-1] - 1
            H[i, j] = max(p1, p2, p3)
    return H

Testing:

In [5]:
print(smith_matrix('acbababa', 'abababda'))

[[ 0  0  0  0  0  0  0  0  0]
 [ 0  2  1  2  1  2  1  0  2]
 [ 0  1  1  1  1  1  1  0  1]
 [ 0  0  3  2  3  2  3  2  1]
 [ 0  2  2  5  4  5  4  3  4]
 [ 0  1  4  4  7  6  7  6  5]
 [ 0  2  3  6  6  9  8  7  8]
 [ 0  1  4  5  8  8 11 10  9]
 [ 0  2  3  6  7 10 10 10 12]]


### Smith-Waterman with H and P matrices - bottom up

In [6]:
def smith_waterman(X, Y):
    n, m = len(X), len(Y)
    H = np.zeros((n + 1, m + 1), np.int)
    P = np.zeros((n + 1, m + 1), np.int)
    
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            if X[i-1] == Y[j-1]:
                p1 = H[i-1, j-1] + 2
            else:
                p1 = H[i-1, j-1] - 1
            p2 = H[i-1, j] - 1
            p3 = H[i, j-1] - 1
            H[i, j] = max(p1, p2, p3)
            
            if H[i, j] == p1:
                P[i, j] = 1 #1 is the up left arrow
            else:
                if H[i, j] == p2:
                    P[i, j] = 2 #2 is the up arrow
                else:
                    P[i, j] = 3 #3 is the left arrow       
    
    return H, P

Testing:

In [7]:
print('H is: \n', smith_waterman('acbababa', 'abababda')[0])
print('\nP is: \n', smith_waterman('acbababa', 'abababda')[1])

H is: 
 [[ 0  0  0  0  0  0  0  0  0]
 [ 0  2  1  2  1  2  1  0  2]
 [ 0  1  1  1  1  1  1  0  1]
 [ 0  0  3  2  3  2  3  2  1]
 [ 0  2  2  5  4  5  4  3  4]
 [ 0  1  4  4  7  6  7  6  5]
 [ 0  2  3  6  6  9  8  7  8]
 [ 0  1  4  5  8  8 11 10  9]
 [ 0  2  3  6  7 10 10 10 12]]

P is: 
 [[0 0 0 0 0 0 0 0 0]
 [0 1 3 1 3 1 3 3 1]
 [0 2 1 2 1 2 1 1 2]
 [0 2 1 3 1 3 1 3 3]
 [0 1 2 1 3 1 3 3 1]
 [0 2 1 2 1 3 1 3 3]
 [0 1 2 1 2 1 3 3 1]
 [0 2 1 2 1 2 1 3 3]
 [0 1 2 1 2 1 2 1 1]]


### Align X and Align Y print functions

In [8]:
def smith_alignX(X, P, n, m):
    if P[n][m] == 1:
        smith_alignX(X, P, n-1, m-1)
        print(X[n-1])
    else:
        if P[n][m] == 3:
            smith_alignX(X, P, n, m - 1)
            print('-')
        elif P[n][m] == 2:
            smith_alignX(X, P, n - 1, m)
            print(X[n-1])   

In [9]:
def smith_alignY(Y, P, n, m):
    if P[n][m] == 1:
        smith_alignY(Y, P, n-1, m-1)
        print(Y[m-1])
    else:
        if P[n][m] == 2:
            smith_alignY(Y, P, n-1, m)
            print('-')
        elif P[n][m] == 3:
            smith_alignY(Y, P, n, m-1)
            print(Y[m-1])  

Testing:

In [14]:
X = 'cdbaabbdca'
Y = 'cadcaccabd'
n = len(X)
m = len(Y)
H = smith_waterman(X, Y)[0]
P = smith_waterman(X, Y)[1]

smith_alignX(X, P, n, m)
print('---------')
smith_alignY(Y, P, n, m)

c
-
d
b
a
-
-
a
b
b
d
c
a
---------
c
a
d
c
a
c
c
a
-
b
d
-
-


### Complete Smith-Waterman function to output H, P, max. alignment, X' and Y' - bottom up

In [15]:
def smith_complete(X,Y):
    n = len(X)
    m = len(Y)
    H = smith_waterman(X, Y)[0]
    P = smith_waterman(X, Y)[1]
    
    print('H is: \n', H, "\n")
    print('P is: \n', P, "\n")
    print('Maximum alignment is: ', H[n,m], '\n')
    
    print("X' is:")
    smith_alignX(X, P, n, m)
    print('\n')
    print("Y' is:")
    smith_alignY(Y, P, n, m)
    

Testing:

In [16]:
smith_complete('caacbdacca', 'bccbcdccba')

H is: 
 [[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0 -1  2  2  1  2  1  2  2  1  0]
 [ 0 -1  1  1  1  1  1  1  1  1  3]
 [ 0 -1  0  0  0  0  0  0  0  0  3]
 [ 0 -1  1  2  1  2  1  2  2  1  2]
 [ 0  2  1  1  4  3  2  1  1  4  3]
 [ 0  1  1  0  3  3  5  4  3  3  3]
 [ 0  0  0  0  2  2  4  4  3  2  5]
 [ 0 -1  2  2  1  4  3  6  6  5  4]
 [ 0 -1  1  4  3  3  3  5  8  7  6]
 [ 0 -1  0  3  3  2  2  4  7  7  9]] 

P is: 
 [[0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 3 1 3 1 1 3 3]
 [0 1 2 1 1 2 1 2 1 1 1]
 [0 1 2 1 1 1 1 1 1 1 1]
 [0 1 1 1 3 1 3 1 1 3 2]
 [0 1 3 2 1 3 3 2 1 1 3]
 [0 2 1 1 2 1 1 3 3 2 1]
 [0 2 1 1 2 1 2 1 1 1 1]
 [0 1 1 1 2 1 2 1 1 3 2]
 [0 1 1 1 3 1 1 1 1 3 3]
 [0 1 2 2 1 1 1 2 2 1 1]] 

Maximum alignment is:  9 

X' is:
c
a
a
c
b
-
d
a
c
c
-
a


Y' is:
c
-
-
c
b
c
d
-
c
c
b
a


### Smith-Waterman Top-down with Memoization

In [17]:
#Note: initialize M as values that cannot be in matrix to determine if we have computed already
#Note: minimum value for any element is -n or -m, so our bound will be -max(n,m) - 1

def smith_memo(X, Y):
    n, m = len(X), len(Y)
    bound = -max(n, m) - 1
    
    M = np.full((n+1, m+1), bound, dtype=int)
    P = np.zeros((n + 1, m + 1), np.int)
    
    for i in range(0, n+1): M[i,0] = 0
    for j in range(0, m+1): M[0,j] = 0
    
    for i in range(1, n + 1):
        for j in range(1, n + 1):
            if M[i,j] != bound:  #memoization: checks if value has already been computed
                M[i,j] = M[i,j]
            elif X[i-1] == Y[j-1]:
                p1 = M[i-1, j-1] + 2
            else:
                p1 = M[i-1, j-1] - 1
            p2 = M[i-1, j] - 1
            p3 = M[i, j-1] - 1
            M[i, j] = max(p1, p2, p3)
            
            
            if M[i, j] == p1:
                P[i, j] = 1 #1 is the up left arrow
            else:
                if M[i, j] == p2:
                    P[i, j] = 2 #2 is the up arrow
                else:
                    P[i, j] = 3 #3 is the left arrow 
            
            
    return M, P
    
    
    

Testing:

In [18]:
X, Y = 'caacbdacca', 'bccbcdccba'
print(smith_waterman(X, Y)[0])
print(smith_memo(X, Y)[0])
print(smith_waterman(X, Y)[1])
print(smith_memo(X, Y)[1])

[[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0 -1  2  2  1  2  1  2  2  1  0]
 [ 0 -1  1  1  1  1  1  1  1  1  3]
 [ 0 -1  0  0  0  0  0  0  0  0  3]
 [ 0 -1  1  2  1  2  1  2  2  1  2]
 [ 0  2  1  1  4  3  2  1  1  4  3]
 [ 0  1  1  0  3  3  5  4  3  3  3]
 [ 0  0  0  0  2  2  4  4  3  2  5]
 [ 0 -1  2  2  1  4  3  6  6  5  4]
 [ 0 -1  1  4  3  3  3  5  8  7  6]
 [ 0 -1  0  3  3  2  2  4  7  7  9]]
[[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0 -1  2  2  1  2  1  2  2  1  0]
 [ 0 -1  1  1  1  1  1  1  1  1  3]
 [ 0 -1  0  0  0  0  0  0  0  0  3]
 [ 0 -1  1  2  1  2  1  2  2  1  2]
 [ 0  2  1  1  4  3  2  1  1  4  3]
 [ 0  1  1  0  3  3  5  4  3  3  3]
 [ 0  0  0  0  2  2  4  4  3  2  5]
 [ 0 -1  2  2  1  4  3  6  6  5  4]
 [ 0 -1  1  4  3  3  3  5  8  7  6]
 [ 0 -1  0  3  3  2  2  4  7  7  9]]
[[0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 3 1 3 1 1 3 3]
 [0 1 2 1 1 2 1 2 1 1 1]
 [0 1 2 1 1 1 1 1 1 1 1]
 [0 1 1 1 3 1 3 1 1 3 2]
 [0 1 3 2 1 3 3 2 1 1 3]
 [0 2 1 1 2 1 1 3 3 2 1]
 [0 2 1 1 2 1 2 1 1 1 1]
 [0 1 